// IPC channel 名的单一真源:main 注册与 preload 调用共同引用,
// 拼写不一致会直接变成编译错误,而不是运行时静默挂起。
export const IpcChannel = {
  ProjectsList: 'projects:list',
  ProjectsSelectFolder: 'projects:select-folder',
  ProjectsCreate: 'projects:create',
  ProjectsRemove: 'projects:remove',
  ProjectsReveal: 'projects:reveal',
  CommandsList: 'commands:list',
  CommandsCreate: 'commands:create',
  CommandsUpdate: 'commands:update',
  CommandsRemove: 'commands:remove',
  CommandsStart: 'commands:start',
  CommandsStop: 'commands:stop',
  CommandsStatuses: 'commands:statuses',
  CommandsLogs: 'commands:logs',
  CommandsLogEvent: 'commands:log',
  TasksList: 'tasks:list',
  TasksCreate: 'tasks:create',
  TasksUpdate: 'tasks:update',
  TasksRemove: 'tasks:remove',
  TasksCompletedBetween: 'tasks:completed-between',
  TaskNotesList: 'tasks:notes:list',
  TaskNotesCreate: 'tasks:notes:create',
  TaskNotesRemove: 'tasks:notes:remove',
  TaskChecklistList: 'tasks:checklist:list',
  TaskChecklistCreate: 'tasks:checklist:create',
  TaskChecklistToggle: 'tasks:checklist:toggle',
  TaskChecklistRemove: 'tasks:checklist:remove',
  ReportsGet: 'reports:get',
  ReportsSave: 'reports:save',
  ReportsDates: 'reports:dates',
  PromptsList: 'prompts:list',
  PromptsCreate: 'prompts:create',
  PromptsUpdate: 'prompts:update',
  PromptsRemove: 'prompts:remove',
  PromptsImportFiles: 'prompts:import-files',
  SkillsList: 'skills:list',
  SkillsOpen: 'skills:open',
  AppInfo: 'app:info'
} as const

export type IpcChannelName = (typeof IpcChannel)[keyof typeof IpcChannel]
